/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as RecordRouteImport } from './routes/record'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreAdminRouteImport } from './routes/store.admin'
import { Route as StoreOrderRouteImport } from './routes/store.order'
import { Route as StorePrivacyRouteImport } from './routes/store.privacy'
import { Route as StoreTermsRouteImport } from './routes/store.terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAdminRoute = StoreAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderRoute = StoreOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacyRoute = StorePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTermsRoute = StoreTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/camera': typeof CameraRoute
  '/contacts': typeof ContactsRoute
  '/diary': typeof DiaryRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/record': typeof RecordRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRouteWithChildren
  '/sync': typeof SyncRoute
  '/tasks': typeof TasksRoute
  '/translate': typeof TranslateRoute
  '/trips': typeof TripsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/store/admin': typeof StoreAdminRoute
  '/store/order': typeof StoreOrderRoute
  '/store/privacy': typeof StorePrivacyRoute
  '/store/terms': typeof StoreTermsRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/camera': typeof CameraRoute
  '/contacts': typeof ContactsRoute
  '/diary': typeof DiaryRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/record': typeof RecordRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/tasks': typeof TasksRoute
  '/translate': typeof TranslateRoute
  '/trips': typeof TripsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/store/admin': typeof StoreAdminRoute
  '/store/order': typeof StoreOrderRoute
  '/store/privacy': typeof StorePrivacyRoute
  '/store/terms': typeof StoreTermsRoute
  '/store': typeof StoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/camera': typeof CameraRoute
  '/contacts': typeof ContactsRoute
  '/diary': typeof DiaryRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/record': typeof RecordRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRouteWithChildren
  '/sync': typeof SyncRoute
  '/tasks': typeof TasksRoute
  '/translate': typeof TranslateRoute
  '/trips': typeof TripsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/store/admin': typeof StoreAdminRoute
  '/store/order': typeof StoreOrderRoute
  '/store/privacy': typeof StorePrivacyRoute
  '/store/terms': typeof StoreTermsRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activate'
    | '/admin'
    | '/appointments'
    | '/calculator'
    | '/calendar'
    | '/camera'
    | '/contacts'
    | '/diary'
    | '/guide'
    | '/login'
    | '/meetings'
    | '/messages'
    | '/notes'
    | '/onboarding'
    | '/projects'
    | '/receive'
    | '/record'
    | '/register'
    | '/reminders'
    | '/settings'
    | '/store'
    | '/sync'
    | '/tasks'
    | '/translate'
    | '/trips'
    | '/projects/$id'
    | '/store/admin'
    | '/store/order'
    | '/store/privacy'
    | '/store/terms'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activate'
    | '/admin'
    | '/appointments'
    | '/calculator'
    | '/calendar'
    | '/camera'
    | '/contacts'
    | '/diary'
    | '/guide'
    | '/login'
    | '/meetings'
    | '/messages'
    | '/notes'
    | '/onboarding'
    | '/projects'
    | '/receive'
    | '/record'
    | '/register'
    | '/reminders'
    | '/settings'
    | '/sync'
    | '/tasks'
    | '/translate'
    | '/trips'
    | '/projects/$id'
    | '/store/admin'
    | '/store/order'
    | '/store/privacy'
    | '/store/terms'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activate'
    | '/admin'
    | '/appointments'
    | '/calculator'
    | '/calendar'
    | '/camera'
    | '/contacts'
    | '/diary'
    | '/guide'
    | '/login'
    | '/meetings'
    | '/messages'
    | '/notes'
    | '/onboarding'
    | '/projects'
    | '/receive'
    | '/record'
    | '/register'
    | '/reminders'
    | '/settings'
    | '/store'
    | '/sync'
    | '/tasks'
    | '/translate'
    | '/trips'
    | '/projects/$id'
    | '/store/admin'
    | '/store/order'
    | '/store/privacy'
    | '/store/terms'
    | '/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CalculatorRoute: typeof CalculatorRoute
  CalendarRoute: typeof CalendarRoute
  CameraRoute: typeof CameraRoute
  ContactsRoute: typeof ContactsRoute
  DiaryRoute: typeof DiaryRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MessagesRoute: typeof MessagesRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReceiveRoute: typeof ReceiveRoute
  RecordRoute: typeof RecordRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRouteWithChildren
  SyncRoute: typeof SyncRoute
  TasksRoute: typeof TasksRoute
  TranslateRoute: typeof TranslateRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/admin': {
      id: '/store/admin'
      path: '/admin'
      fullPath: '/store/admin'
      preLoaderRoute: typeof StoreAdminRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/order': {
      id: '/store/order'
      path: '/order'
      fullPath: '/store/order'
      preLoaderRoute: typeof StoreOrderRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/privacy': {
      id: '/store/privacy'
      path: '/privacy'
      fullPath: '/store/privacy'
      preLoaderRoute: typeof StorePrivacyRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/terms': {
      id: '/store/terms'
      path: '/terms'
      fullPath: '/store/terms'
      preLoaderRoute: typeof StoreTermsRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface StoreRouteChildren {
  StoreAdminRoute: typeof StoreAdminRoute
  StoreOrderRoute: typeof StoreOrderRoute
  StorePrivacyRoute: typeof StorePrivacyRoute
  StoreTermsRoute: typeof StoreTermsRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAdminRoute: StoreAdminRoute,
  StoreOrderRoute: StoreOrderRoute,
  StorePrivacyRoute: StorePrivacyRoute,
  StoreTermsRoute: StoreTermsRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  CalculatorRoute: CalculatorRoute,
  CalendarRoute: CalendarRoute,
  CameraRoute: CameraRoute,
  ContactsRoute: ContactsRoute,
  DiaryRoute: DiaryRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MessagesRoute: MessagesRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReceiveRoute: ReceiveRoute,
  RecordRoute: RecordRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRouteWithChildren,
  SyncRoute: SyncRoute,
  TasksRoute: TasksRoute,
  TranslateRoute: TranslateRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
